bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=grey"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'  # default is fg=8, it is not clear under solarized-dark
